#!/usr/bin/env python3
"""
visualize_ecg_annotations.py

Visualizes spatial annotations (lead bounding boxes, lead text boxes, and plotted signal pixels)
generated by ecg-image-kit onto synthetic ECG images.
"""

import os
import sys
import json
import argparse
import numpy as np
import cv2
from PIL import Image, ImageDraw, ImageFont

def parse_args():
    parser = argparse.ArgumentParser(description="Visualize ECG bounding boxes and signal annotations on synthetic ECG images.")
    parser.add_argument("-i", "--image_path", type=str, required=True, help="Path to the synthetic ECG image (.png)")
    parser.add_argument("-j", "--json_path", type=str, default=None, help="Path to the JSON sidecar file (autodetected if omitted)")
    parser.add_argument("-o", "--output_path", type=str, default=None, help="Output path for annotated image")
    parser.add_argument("--show_lead_bbox", action="store_true", default=True, help="Draw lead bounding boxes")
    parser.add_argument("--show_text_bbox", action="store_true", default=True, help="Draw lead name text bounding boxes")
    parser.add_argument("--show_pixels", action="store_true", default=False, help="Overlay plotted signal pixels")
    return parser.parse_args()

def draw_polygon(img, pts, color, thickness=2, label=None):
    """
    Draws a polygon from [y, x] points on an OpenCV image.
    pts is expected in [[y1, x1], [y2, x2], [y3, x3], [y4, x4]] format.
    """
    if not pts or len(pts) < 4:
        return
    # Convert from [y, x] to OpenCV [x, y] format
    cv_pts = np.array([[int(round(pt[1])), int(round(pt[0]))] for pt in pts], np.int32)
    cv_pts = cv_pts.reshape((-1, 1, 2))
    cv2.polylines(img, [cv_pts], isClosed=True, color=color, thickness=thickness)

    if label:
        x_min = int(min(pt[1] for pt in pts))
        y_min = int(min(pt[0] for pt in pts))
        cv2.putText(img, label, (x_min + 5, y_min + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2, cv2.LINE_AA)

def visualize_annotations(image_path, json_path=None, output_path=None, show_lead_bbox=True, show_text_bbox=True, show_pixels=False):
    if not os.path.exists(image_path):
        print(f"Error: Image path {image_path} does not exist.")
        sys.exit(1)

    if json_path is None:
        base, _ = os.path.splitext(image_path)
        json_path = base + ".json"

    if not os.path.exists(json_path):
        print(f"Error: JSON metadata path {json_path} does not exist.")
        sys.exit(1)

    # Load image and JSON
    img = cv2.imread(image_path)
    if img is None:
        print(f"Error: Unable to load image at {image_path}")
        sys.exit(1)

    with open(json_path, "r") as f:
        meta = json.load(f)

    leads = meta.get("leads", [])
    if not leads:
        print("Warning: No 'leads' array found in JSON metadata.")

    # Distinct colors (BGR) for leads
    lead_colors = [
        (0, 165, 255),  # Orange
        (255, 0, 0),    # Blue
        (0, 255, 0),    # Green
        (255, 0, 255),  # Magenta
        (0, 255, 255),  # Yellow
        (128, 0, 128),  # Purple
        (0, 128, 255),  # Dark Orange
        (255, 128, 0),  # Cyan-Blue
        (0, 200, 100),  # Mint
        (100, 100, 255),# Light Red
        (255, 192, 203),# Pink
        (128, 128, 0)   # Teal
    ]

    for idx, lead in enumerate(leads):
        lead_name = lead.get("lead_name", f"Lead_{idx}")
        color = lead_colors[idx % len(lead_colors)]

        # Draw lead bounding box
        if show_lead_bbox and "lead_bounding_box" in lead:
            bbox = lead["lead_bounding_box"]
            pts = [bbox.get("0"), bbox.get("1"), bbox.get("2"), bbox.get("3")]
            draw_polygon(img, pts, color=color, thickness=2, label=f"Box: {lead_name}")

        # Draw text label bounding box
        if show_text_bbox and "text_bounding_box" in lead:
            tbox = lead["text_bounding_box"]
            pts = [tbox.get("0"), tbox.get("1"), tbox.get("2"), tbox.get("3")]
            draw_polygon(img, pts, color=(0, 0, 255), thickness=2, label=f"Text: {lead_name}")

        # Draw plotted signal pixels
        if show_pixels and "plotted_pixels" in lead:
            pixels = lead["plotted_pixels"]
            for px in pixels:
                y, x = int(round(px[0])), int(round(px[1]))
                if 0 <= y < img.shape[0] and 0 <= x < img.shape[1]:
                    img[y, x] = (0, 0, 255) # Red dot

    if output_path is None:
        base, ext = os.path.splitext(image_path)
        output_path = base + "_annotated.png"

    cv2.imwrite(output_path, img)
    print(f"Successfully saved visual annotations to: {output_path}")
    return output_path

if __name__ == "__main__":
    args = parse_args()
    visualize_annotations(
        image_path=args.image_path,
        json_path=args.json_path,
        output_path=args.output_path,
        show_lead_bbox=args.show_lead_bbox,
        show_text_bbox=args.show_text_bbox,
        show_pixels=args.show_pixels
    )
